services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  redis:
    image: redis:7-alpine
    networks:
      - backend

  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SETTINGS_MODULE=zhtest.settings
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery_worker:
    build:
      context: .
    command: celery -A zhtest.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SETTINGS_MODULE=zhtest.settings
    networks:
      - backend

  celery_beat:
    build:
      context: .
    command: celery -A zhtest.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - backend
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SETTINGS_MODULE=zhtest.settings

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: celery -A zhtest.celery_app flower --loglevel=info
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=zhtest.settings

volumes:
  postgres_data:

networks:
  backend: